# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

def install_pods
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!
    pod 'R.swift'       , '~> 5.0.3'
    pod 'SnapKit'       , '~> 5.0.0'
    pod 'SVProgressHUD' , '~> 2.2.5'
    pod 'Moya', '~> 13.0'
    pod 'DynamicButton' , '~> 6.1.0'
    pod 'SPPermission/Camera'
    pod 'Material', '~> 3.1.0'
    pod 'SwiftLint'
    pod 'IQKeyboardManagerSwift'
    pod 'Pring'
    pod 'QRCodeReader.swift', '~> 10.1.0'
    
    pod 'Firebase/Core'
    pod 'Firebase/Firestore' 
    pod 'Eureka'

    #Pods for FiMap

 target 'emsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ems' do
    install_pods
end


swift3_names = [
]

swift4_names = [

]

swift42_names = [

]

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if swift4_names.include? target.name
                config.build_settings['SWIFT_VERSION'] = "4.0"
               elsif swift42_names.include? target.name
                config.build_settings['SWIFT_VERSION'] = "4.2"
               elsif swift3_names.include? target.name
                config.build_settings['SWIFT_VERSION'] = "3.0"
               else
                config.build_settings['SWIFT_VERSION'] = "5.0"
            end
        end
    end
end

